### ISSUE TITLE
add extension to packagist.org

### ISSUE THREAD

**Issue by giuseppemorelli** [facebookincubator/facebook-for-magento#101]
Hi,
thank you for your great extension.

It is possible to add your module to packagist.org?

**Comment by dmitridr** [comment]
Hi,

Glad you like our extension. 
Yeah I think we can add it, I will look into it.

**Comment by dmitridr** [comment]
@giuseppemorelli  Thanks for your interest and patience. This has now been done.

https://packagist.org/packages/facebook/facebook-for-magento

**Comment by giuseppemorelli** [comment]
Thank you so much  @dmitridr !
