### ISSUE TITLE
Facebook Business Users

### ISSUE THREAD

**Issue by TheBlogHouse** [facebookincubator/facebook-for-magento#15]
Hi.

We are trying to set this up for a client but no matter what we do we get the following error:

> It looks like you have more than one advert account.
> Because you have more than one advert account, we don't know which one to create a pixel in. To continue, please go to the Pixels section in Adverts Manager and create a pixel in the account you'd like to use for this store. Once you've created your pixel, you can restart this plugin and we'll install it on your site at this step. Learn more about creating a pixel.

We have the pixel id and it's set up manually within our business account but there is no way to enter this in Magento as we can't get past the Get Started wizard and https://www.facebook.com/ads/dia?origin=https%3A%2F%2Fwww.OurWebsite.com

Thanks

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in.

I've seen this problem before, if you have created a pixel you must assign it to an ad account. Once this is done, the pixel step should show your pixel during setup. Pixels that are not assigned to any ad account will not show in that selector.

This article describes the necessary steps, look for the section that says `Assign Ad Account` :
https://www.jonloomer.com/2017/03/17/share-facebook-audience-pixel/

Let us know if that helps.

**Comment by dmitridr** [comment]
Please re-open the issue if this did not solve your problem.
