### ISSUE TITLE
Feed Generation is Running out of memory : Potential Memory Leak?

### ISSUE THREAD

**Issue by pawelrox** [facebookincubator/facebook-for-magento#17]
Hi there, just installed your extension on Magento and came across this issue twice now. Allowed memory is set to 1024MB and that's when it breaks. Could you provide a workaround or some other alternative?

Error message
E_ERROR: Allowed memory size of 1048576000 bytes exhausted (tried to allocate 78 bytes)

Stack trace
…alled at .../lib/Zend/Db/Statement/Pdo.php (291)
…ed at .../lib/Zend/Db/Adapter/Abstract.php (738)
…/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php (1109)
…/app/code/core/Mage/Catalog/Model/Resource/Product/Collection.php (480)
…/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php (874)
…lled at .../lib/Varien/Data/Collection.php (741)
…/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php (389)
…/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php (331)
…/app/code/community/Facebook/AdsExtension/Model/Observer.php (134)
…/app/code/community/Facebook/AdsExtension/controllers/Adminhtml/FbregenController.php (41)
…/app/code/community/Facebook/AdsExtension/controllers/Adminhtml/FbregenController.php (32)
…/app/code/core/Mage/Core/Controller/Varien/Action.php (418)
…/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php (250)
…/app/code/core/Mage/Core/Controller/Varien/Front.php (172)
…/app/code/core/Mage/Core/Model/App.php (354)
…_Model_App::run called at .../app/Mage.php (684)
in Mage::run called at .../index.php (98)

**Comment by pawelrox** [comment]
I have managed to use data feed manager on magento and then link it up in Facebook Business Manager > Product Catalogues > Product Feeds

**Comment by dmitridr** [comment]
Glad you found a workaround. We'll keep this issue open to address the memory leak when generating feed, since there seems to be one.

**Comment by pawelrox** [comment]
It might be worth noting that when I was testing it locally(Mac OS) it worked perfectly fine but memory leak happened in production.

**Comment by punkstar** [comment]
We've experienced memory leaks when using this extension too.  We solved it by stopping a [forced reload of the product model](https://github.com/facebookincubator/facebook-for-magento/blob/5987385a31e8806345febd186bb9f9630dd586f2/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php#L391) and adding a `$product->clearInstance()` at the end of each iteration of the foreach [here](https://github.com/facebookincubator/facebook-for-magento/blob/5987385a31e8806345febd186bb9f9630dd586f2/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php#L389).

**Comment by dmitridr** [comment]
@punkstar Great find! Would you be willing to send us a pull request with the 2 lines so we can give you credit? If not, we can add it ourselves for the next version.

**Comment by vipulmishra341** [comment]
@dmitridr can you please let me know when can you add these changes in the module?

**Comment by dmitridr** [comment]
Was hoping we could get a pull request for this. But if we don't get one, we'll try adding it ourselves for the next release. ETA ~1 week.

**Comment by dmitridr** [comment]
Got a repro on the memory leak, we have a fix ready, should be out in a few days.

**Comment by dmitridr** [comment]
Thanks y'all for your patience. The fix is ready in [v2.3.5](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.3.5) please try it, and if the problem still occurs let us know by opening a new issue and referencing this one.

**Comment by dmitridr** [comment]
Thanks @punkstar for the suggested fix! We pretty much went with this approach.
