### ISSUE TITLE
Support catalogues containing multibyte characters

### ISSUE THREAD

**Issue by punkstar** [facebookincubator/facebook-for-magento#19]
This Magento extension currently makes use of string manipulation functions that are not multibyte safe.  This means that the character limit enforcement in `FBProductFeed::buildProductAttrText`, for example, can end up producing invalid UTF-8 output.

I'm afraid I can't provide a diff for the work that we've had to do to get this to work due to the level of customisation that we've made to the file already, but an easy win would be to search and replace `substr` and `strlen` in that file and replace with their multi-byte counterparts - `mb_substr` and `mb_strlen`.

**Comment by punkstar** [comment]
Could be related to #13.

**Comment by dmitridr** [comment]
Hello,

Thanks for flagging this. If you change your mind about the diff, please feel free to send us a pull request, we're very happy to review. Failing that, if you provide us a description which we can use to test and repro the problem, we can probably solve this more quickly than otherwise.

**Comment by dmitridr** [comment]
We found that this was related to the blank screen issue, oddly enough. It was fixed in https://github.com/facebookincubator/facebook-for-magento/commit/0149373994f704486cc349bf44879c6bf3d434ea which was based on #45.
