### ISSUE TITLE
Facebook Page Shop support

### ISSUE THREAD

**Issue by dakira** [facebookincubator/facebook-for-magento#26]
It would be great to use this plugin as a direct feed for the Facebook Page Shop. As #9 was closed I'm creating a new issue here as per @dmitridr s instructions.

**Comment by dmitridr** [comment]
Thanks! We'll keep this open for now as a feature request. Sounds like there is a lot of interest here from the previous issue so we're definitely open to the idea.

**Comment by royfung** [comment]
i also need to get products from magento to fb shop & market place.

**Comment by dmitridr** [comment]
Going to start working on this. I think ETA ~1 month for support of auto shop creation as an advanced feature.

**Comment by Winsa** [comment]
Hello @dmitridr :)

I'm also looking for this feature! How close will it be to the shopify version & woocommerce version? When i'm asking as ''how close'' i mean, will it show up with the same layout on facebook, like this?:
![skaermbillede 2018-03-04 kl 18 09 58](https://user-images.githubusercontent.com/37045918/36948201-5d5406d0-1fd7-11e8-869a-2b6cf168095c.png)
![skaermbillede 2018-03-04 kl 18 10 07](https://user-images.githubusercontent.com/37045918/36948202-5d731110-1fd7-11e8-8d9b-6073b3eaf775.png)

**Comment by dmitridr** [comment]
Yes, same layout. The difference will be that specific sizes/colors/etc will not be able to be selected, and the 'Checkout' button will take you to the product page on your site.

I have good news : I have the code ready for this and I'm testing it now. I should have a new plugin version for y'all by early next week which will enable shop creation.

**Comment by Winsa** [comment]
Hello @dmitridr :)

Looking forward to try the initial test. Please let us now, when we can download it / try it out.

Best regards, Winsa

**Comment by dmitridr** [comment]
@Winsa @dakira @royfung 
v2.4.0 is out and available [here](https://github.com/facebookincubator/facebook-for-magento/releases/tag/2.4.0). There are instructions on that page on how to get shops working with the plugin, but unfortunately you will have to reset your existing installations to get the shop, which may affect any running ads, please keep that in mind!

**Comment by Winsa** [comment]
Can’t Wait for Step 5. Thank you so much!

Bedste hilsner,

Behruz Jahangiri

**Comment by dmitridr** [comment]
Great, I am closing this for now, but if there is a problem with the new shops feature, please open an issue. We may be able to help depending on the issue.
