### ISSUE TITLE
There no Facebook tab on Magento admin menu after plugin installation

### ISSUE THREAD

**Issue by dzonasb** [facebookincubator/facebook-for-magento#28]
Installation of plugin was successful, but there no facebook tab on Magento admin panel. How can I solve it?

**Comment by dmitridr** [comment]
I guess it appeared for you? Curious why it didn't at first, maybe it was a cache issue?

**Comment by dzonasb** [comment]
Hi Dmitri

Thanks for email. Yes it was ceche problem. I dont find where to delete my
topic so just close issue

Regards
Jonas

2018-01-26 09:12 PM "Dmitri Dranishnikov" <notifications@github.com> rašė:
