### ISSUE TITLE
Wrong Conversion Value reported in Facebook Ads after installation

### ISSUE THREAD

**Issue by ariskos1** [facebookincubator/facebook-for-magento#29]
Hello,
I installed v.2.3.6 on a Magento 1.8 version.
After setting up the plugin, I started showing an abnormal number of Facebook conversions and Converion Value.
It seems that when a user, coming from Facebook ads, views a product then FB ads report it as it was a purchase by adding its price to FB ads interface as a conversion.
![image](https://user-images.githubusercontent.com/35804566/35389661-415a4246-01e1-11e8-861b-1ea0ae6d6256.png)
On the other hand, when you actually make a purchase from the eshop, in the thank-you page there is no FB purchase event to notify FB ads that a purchase was made and fetch its price.
![toiles-thank-you-page](https://user-images.githubusercontent.com/35804566/35389778-a4ff6592-01e1-11e8-8bd3-f98dcb373a18.png)
Is there any option that I am missing and how could I solve this problem?

**Comment by dmitridr** [comment]
Hey,

The term `Conversion` is extremely misleading, it actually depends on the Ad, and does not necessarily equal `Purchases` (Sometimes it's clicks/views). If you are viewing the ads insights in ads manager, you can add the `Purchases` column to your reporting, which will show you the true # of Purchases the Ad drove.

The lack of Purchase event seems to be a bug, it should fire a purchase event after purchase. Could you go into some detail about how your purchase flow is configured, do you have some custom plugins for the checkout flow? I could try to set up something similar and debug it to see if I have the same problem.

It may take some time though, as I have to prioritize other work in the near term.

**Comment by dmitridr** [comment]
Closing this because it's been 2 months. Please open a new issue if it's still a problem.
