### ISSUE TITLE
Not all products are being added to catalogue 

### ISSUE THREAD

**Issue by bedroomathletics** [facebookincubator/facebook-for-magento#3]
Hi there,

After setting up the feed, not all products are being uploaded to my catalogue. 

![image](https://user-images.githubusercontent.com/32071663/30552333-7fa0abfa-9c95-11e7-9fdf-9f7c8d975c31.png)

574 products in inventory. 

![image](https://user-images.githubusercontent.com/32071663/30552360-93b6ffa4-9c95-11e7-9ba3-adb07ef1f1fb.png)

Only 141 products added.

Hope you can help!

Kade.
BEdroom Athletics.

**Comment by dmitridr** [comment]
Hi, 

I checked your feed tsv file, It has all 574 products right now. So you should be ok once the next daily scheduled upload comes around. If you don't want to wait, you can click on your product feed 'Magento Products' in the 2nd screenshot, then go to 'Settings' and hit 'Fetch Now'.

From our logs, it seems like in the past, your feed generation crashed on the store side after generating 141 products, I am not sure why. If you have any PHP or Magento exception logs you can share those would be helpful.

**Comment by dmitridr** [comment]
Looks like the past few uploads have uploaded the full product catalog, as expected. I'm closing this issue for now, but feel free to re-open if it happens again.
