### ISSUE TITLE
error "Property id must have entirely unique values for all items in this feed"

### ISSUE THREAD

**Issue by ktsixit** [facebookincubator/facebook-for-magento#30]
Hi,

There are 198 products that appear multiple times in facebook feed file (generated in media/facebook_adstoolbox_product_feed.tsv). 

As a result I'm getting the following error in reports:

`"Some products or properties were rejected because of the following: Non-Unique Value: id"`

There are no products with the same id in my store. It's just that the facebook extension is mentioning some products again and again, with the same data in .tsv file.

How can I fix that? What may be the reason for this issue?

**Comment by mengyingdu** [comment]
Hi @ktsixit ,

I can help you by looking into our remote logging. What's your site url or fb page url?

Also, where did you see the reports? Is that in your catalog manager? A screen shot could be better.

Thanks.

**Comment by ktsixit** [comment]
Here are some screenshots:

![fb_catalog_error](https://user-images.githubusercontent.com/2758872/35625456-1bad8d8c-069b-11e8-9c1e-5f8bc52c4451.jpg)

![feed-link](https://user-images.githubusercontent.com/2758872/35625459-1dfd4abe-069b-11e8-926f-7942f361ca92.jpg)

![view-feed-details](https://user-images.githubusercontent.com/2758872/35625460-1f158970-069b-11e8-8649-05e24b47c991.jpg)

**Comment by ktsixit** [comment]
Can I send you the url in a private message?

**Comment by ktsixit** [comment]
Bump

**Comment by mengyingdu** [comment]
Hi @ktsixit ,

Sorry for the delayed reply. You can either send your site url here or to ads_extension_woocommerce@fb.com. If you decide to send it by email, you will receive an auto-reply immediately, but I will keep eyes to find your email. Better key words in title will help.
Thanks.

**Comment by ktsixit** [comment]
I have sent an email. Awaiting for response, thank you

**Comment by mengyingdu** [comment]
Hi @ktsixit ,

Did you duplicate this product in your store before? It seems this product has multiple record from your db. 
Can you try : 
1. re-config your settings --> delete your setting
2. re-setup 

It will erase the data from fb side, and sync all current eligible products.
Let me know if you need more help.

Thanks.

**Comment by A-Kits** [comment]
I've had a same issue. I've already re-config  delete setting clear cache  but still found this issue

**Comment by dmitridr** [comment]
Can both of you confirm you are using the latest version of the extension 2.3.6 ? It should be pretty easy for us to add a check for id to avoid duplicating rows. But I'm not sure why multiple rows would load to begin with.

**Comment by ktsixit** [comment]
Yes, I confirm that I'm using the 2.3.6 version of the extension.

**Comment by ktsixit** [comment]
@mengyingdu 
There are no duplicate products in our store, I have already checked that.

**Comment by dmitridr** [comment]
We have a fix for this coming. Should be out in the next version 2.4.1

**Comment by dmitridr** [comment]
Hey @ktsixit and @A-Kits please try v2.4.1 it should fix the duplication problem, you will need to click `Fetch Now` once within the interface. Alternatively you can wait up to 24 hours (or longer if you have a cache) for it to take effect after upgrading.

Please open a new issue and reference this one if you continue to have this problem.
