### ISSUE TITLE
Notice: Undefined index: female in /app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php on line 286

### ISSUE THREAD

**Issue by tiltedlistener** [facebookincubator/facebook-for-magento#34]
I'm running PHP 5.4.45-0+deb7u8. 

On line 286, this conditional should be an isset() check, correct?

```
    if ($this->gender_map[$gender_id]) {
      return $this->gender_map[$gender_id];
    }
```
As in:

```
    if (isset($this->gender_map[$gender_id])) {
      return $this->gender_map[$gender_id];
    }
```

**Comment by dmitridr** [comment]
Hey, Good find! We'll fix it in the next versions, though you can send us a quick pull request to fix it if you like.

**Comment by tiltedlistener** [comment]
Yeah - I can do that later today

**Comment by dmitridr** [comment]
#38 should fix this, so the fix for this will be live in the next version, 2.4.1 which we'll release in the next few days.

**Comment by dmitridr** [comment]
The new version with the fix [is out](https://github.com/facebookincubator/facebook-for-magento/releases)
