### ISSUE TITLE
Fatal error: Class 'Facebook_AdsExtension_Helper_Data' not found Mage.php on line 547

### ISSUE THREAD

**Issue by pggood** [facebookincubator/facebook-for-magento#37]
Installed the plugin crashed my Magento 1.9 had to restore the whole system from a backup Not happy

**Comment by dmitridr** [comment]
Hey, sorry you had this crash. Do you have compilation mode enabled? 
If so, you may need to disable compilation mode during install then recompiling after.

If not, would love to get some more details, do you have a stack trace you could share with us?

**Comment by lannerF** [comment]
I get the same issue on installation. 

> To recover:
> 1. Copy the Facebook_AdsExtension.xml from
> /public_html/app/etc/modules 
> to
> /akross_ca/public_html/app/etc/modules/disabled
> 2. Using SSH run:
> php -r 'require "app/Mage.php"; Mage::app()->getCacheInstance()->flush();'

Now the crash log:

2018-04-04T17:49:55+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Facebook_AdsExtension_Block_ViewContent' in /public_html/app/Mage.php:595
Stack trace:
#0 /public_html/includes/src/__default.php(28682): Mage::throwException('Invalid block t...')
#1 /public_html/includes/src/__default.php(28624): Mage_Core_Model_Layout->_getBlockInstance('Facebook_AdsExt...', Array)
#2 /public_html/includes/src/__default.php(28659): Mage_Core_Model_Layout->createBlock('Facebook_AdsExt...', 'facebook_ads_ex...')
#3 /public_html/includes/src/__default.php(28426): Mage_Core_Model_Layout->addBlock('Facebook_AdsExt...', 'facebook_ads_ex...')
#4 /public_html/includes/src/__default.php(28392): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /public_html/includes/src/__default.php(28397): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /public_html/includes/src/__default.php(14213): Mage_Core_Model_Layout->generateBlocks()
#7 /public_html/includes/src/Mage_Catalog_Helper_Product_View.php(73): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /public_html/includes/src/Mage_Catalog_Helper_Product_View.php(144): Mage_Catalog_Helper_Product_View->initProductLayout(Object(Mage_Catalog_Model_Product), Object(Mage_Catalog_ProductController))
#9 /public_html/app/code/core/Mage/Catalog/controllers/ProductController.php(132): Mage_Catalog_Helper_Product_View->prepareAndRender(273, Object(Mage_Catalog_ProductController), Object(Varien_Object))
#10 /public_html/includes/src/__default.php(14287): Mage_Catalog_ProductController->viewAction()
#11 /public_html/includes/src/__default.php(18764): Mage_Core_Controller_Varien_Action->dispatch('view')
#12 /public_html/includes/src/Ho_OfflineMaintenance_Controller_Router_Standard.php(54): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /public_html/includes/src/__default.php(18294): Ho_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 /public_html/includes/src/__default.php(21210): Mage_Core_Controller_Varien_Front->dispatch()
#15 /public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#16 /public_html/index.php(87): Mage::run('', 'store')
#17 {main}

**Comment by dmitridr** [comment]
Closing since we did not get the necessary information to solve this problem. If you have a stack trace (usually in your server log file) it can help us solve this problem.
