### ISSUE TITLE
Bundle products display price without tax

### ISSUE THREAD

**Issue by vladeta** [facebookincubator/facebook-for-magento#4]
Hello!

I've noticed that bundle products are exported without tax where regular products are exported with tax. Is this something that can be quickly fixed?

Thanks,
Vladeta

**Comment by dmitridr** [comment]
Hello!

Good catch. It should be an easy fix, as you say, probably a one line change [here](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php#L656) to apply the tax via call to `getFinalPrice`. I'll test that and send out a new version soon.

**Comment by dmitridr** [comment]
Tested and released a fix for this in [2.3.2](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.3.2). After upgrading, be sure to hit the `Fetch Now` button to refresh the feed file.

**Comment by vladeta** [comment]
Thanks! Works like a charm! 👍
