### ISSUE TITLE
Misleading Extension

### ISSUE THREAD

**Issue by willryanuk** [facebookincubator/facebook-for-magento#43]
Although free, this extension is rather basic, and there are many other extensions out there that I'd recommend before engaging with this one. 

Fundamentally, this one is not really usable because it does not support multiple store (multi currency) stores, not does it have support for sale prices. These can obviously be added, but there are other off the shelf product feed extensions that already do this, making this one somewhat redundant.

**Comment by dmitridr** [comment]
Thanks for your feedback. We have an open issue to add sale prices in #2 and Facebook itself does not have great multi-currency support at the moment, something that the catalogs team is working on building.
