### ISSUE TITLE
Documentation for installation on staging/development site

### ISSUE THREAD

**Issue by mpalasis** [facebookincubator/facebook-for-magento#44]
Hi, I'd like to be able to install the extension on a staging site to test, instead of directly onto the live production site.
Is there any documentation on what to do for that?
Our staging site is not accessible from the outside, will that be a problem?

**Comment by sammul** [comment]
@mpalasis yes there will be a problem because facebook will not able to send data back. Can you make the staging site accessible(temporary is fine) to outside and try?

**Comment by dmitridr** [comment]
The main problem will be in the feed upload, the feed upload will fail because your staging site is not visible to facebook, so the products won't be able to upload, the pixel installation should still work though.

**Comment by dmitridr** [comment]
Let me follow up here and improve our documentation for how to install this on a dev site. Right now it's not very good, you have to use modman and essentially figure it out on your own.

**Comment by mpalasis** [comment]
I'll leave an extra comment here just to say that so long as you don't intend to push stuff outwards into facebook, there's no problem with installing this extension in a staging environment.
So, it can be included in your main branch/merge bundles just fine.

Issue closed. :)
