### ISSUE TITLE
install the Facebook Ads Extension in magento 1.7.0.2, no get start button

### ISSUE THREAD

**Issue by acronis333** [facebookincubator/facebook-for-magento#46]
I installed the Facebook_Ads module in magento 1.7.0.2 and I did not get the get start button
happens to me with module 2.4.1

With the javascript console these errors appear:

Uncaught SyntaxError: Unexpected token)
(index): 37 Uncaught ReferenceError: Fieldset is not defined
    at (index): 37
(index): 41 Uncaught ReferenceError: Translate is not defined
    at (index): 41
(index): 47 Uncaught ReferenceError: Calendar is not defined
    at (index): 47
(index): 123 Uncaught TypeError: Event.observe is not a function
    at (index): 123
(index): 433 Uncaught ReferenceError: Ajax is not defined
    at (index): 433
(index): 889 Uncaught ReferenceError: $ is not defined
    at (index): 889
(index): 965 Uncaught ReferenceError: $ is not defined
    at (index): 965
(index): 983 Uncaught TypeError: document.observe is not a function
    at (index): 983
(index): 781 Uncaught TypeError: Element.addClassName is not a function
    at HTMLLIElement.onmouseover ((index): 781)
(index): 781 Uncaught TypeError: Element.removeClassName is not a function
    at HTMLLIElement.onmouseout ((index): 781)
(index): 631 Uncaught TypeError: Element.addClassName is not a function
    at HTMLLIElement.onmouseover ((index): 631)
(index): 631 Uncaught TypeError: Element.removeClassName is not a function
    at HTMLLIElement.onmouseout ((index): 631)
(index): 781
....
... a few more lines of error.

Any solution.

Thank you

**Comment by mengyingdu** [comment]
Hi @acronis333,

The errors seem unrelated. What about other plugins you are using now?

Thanks.

**Comment by mengyingdu** [comment]
@dmitridr Can you look into this issue due to the latest release?

**Comment by dmitridr** [comment]
Hey @acronis333, 

Do you have this problem with version 2.4.0 as well? If it's only a problem in 2.4.1 it can help us narrow down the cause. Could you share with us also (1) a screenshot of what you see since you do not see the start button? (2) a screenshot of the full error in the JS console.

**Comment by acronis333** [comment]
Hello
the error is also reproduced with version 2.4.0
attached picture captures and errors thrown by JS console
the total errors when starting the module are 9, and it blocks me to be able to select another element of the main menu, from this moment the other errors that follow are reproduced when I move the mouse for any element of the menu.

Thank you
![seleccion_162](https://user-images.githubusercontent.com/3810181/38076096-e095a5d8-3334-11e8-96cc-240ccd10715b.png)
![seleccion_160](https://user-images.githubusercontent.com/3810181/38076098-e0b55c5c-3334-11e8-9e35-809452f937a3.png)

**Comment by acronis333** [comment]
Sorry for the delay, holidays in my city.
in file exception.log I found this ......

2018-04-03T15:19:20+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Facebook_AdsExtension_Block_AddToCart' in /home/spaciode/public_html/app/Mage.php:594
Stack trace:
#0 /home/spaciode/public_html/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /home/spaciode/public_html/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('Facebook_AdsExt...', Array)
#2 /home/spaciode/public_html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('Facebook_AdsExt...', 'facebook_ads_ex...')
#3 /home/spaciode/public_html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('Facebook_AdsExt...', 'facebook_ads_ex...')
#4 /home/spaciode/public_html/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /home/spaciode/public_html/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /home/spaciode/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /home/spaciode/public_html/app/code/core/Mage/Cms/Helper/Page.php(113): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /home/spaciode/public_html/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'no-route')
#9 /home/spaciode/public_html/app/code/core/Mage/Cms/controllers/IndexController.php(75): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'no-route')
#10 /home/spaciode/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Cms_IndexController->noRouteAction()
#11 /home/spaciode/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('noRoute')
#12 /home/spaciode/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /home/spaciode/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 /home/spaciode/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#15 /home/spaciode/public_html/index.php(87): Mage::run('', 'store')
#16 {main}

Thanks and best regards

**Comment by dmitridr** [comment]
No worries. That could be the cause! I'm swamped right now but I'm going to look into this as soon as I can (probably early next week). 

In the meantime, can you try finding the layout file for the extension (should be in `<magento_dir>/app/design/frontend/base/default/layout/facebook_ads_extension.xml`) and removing the block corresponding to AddToCart. It should be [here](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/design/frontend/base/default/layout/facebook_ads_extension.xml#L8-L10), and seeing if that fixes anything? 

Also one more question : do you have compilation mode enabled?

**Comment by Scarlett-Du** [comment]
Close outdated issue. Feel free to open a new one if you still have this problem, and refer this issue to keep context. Thanks

**Comment by mengyingdu** [comment]
close outdated issue. Feel free to open a new one if you still have this problem and refer this issue ticket to keep context.
