### ISSUE TITLE
Big commerce and facebook shop

### ISSUE THREAD

**Issue by bmwangih** [facebookincubator/facebook-for-magento#49]
@dmitridr  I am having a similar issue as indicated in a previous closed issue and only stumbled upon this forum by a Google search while trying to look for a resolution online.

I intergrated my facebook page with Bigcommerce however on disconnecting my page has been left in an unusable state and no one from facebook seems to be able to assist, 

I know this might be the wrong forum and my apologies for this would you be kind enough to assist me?as am genuinely stuck

**Comment by mengyingdu** [comment]
Hi @bmwangih ,

We don't have the full background about bigcomment integration so it's hard for us to help you. Can you try the advertiser help center?

Thanks.

**Comment by bmwangih** [comment]
Hi @mengyingdu the advertiser help centre has also not been helpful.  Am currently left to my own devices. apologies if this might sound rude but am ready to pay if someone can be able to resolve the issue. I will gladly provide all information required.

Thanks

**Comment by dmitridr** [comment]
@bmwangih 
Hey, I remember there was a similar issue, we solved it by manually deleting the BigCommerce shop and all references to it in our systems. 

Can you give us the name of your page or a link? We can try and delete it for you. 
As proof of identity could you make a post using your page containing the word 'proof'? It should be enough for us to verify that you are the admin.

**Comment by dmitridr** [comment]
I guess the old issue with BC was #9

**Comment by bmwangih** [comment]
@dmitridr thanks for response, The page is "His & Hers Boutique" I have done the below post on the page 
"our satisfied customers are enough proof of our quality items" 
The page link is -https://www.facebook.com/hizandherzboutique/
really grateful for your assistance on this

**Comment by dmitridr** [comment]
Hey @bmwangih it should be all fixed now! You had a lot of BigCommerce shops, like 10 or something in our backend, but I deleted all of them. Your old self-serve shop is visible now : 

https://www.facebook.com/hizandherzboutique/shop

**Comment by bmwangih** [comment]
@dmitridr you the Bomb all good now! 10 shops think I panicked and would connect and disconnect, thanks lots and continue with the superb work!
