### ISSUE TITLE
Only NOSCRIPT version of pixel is firing (Checked via Facebook Pixel Helper)

### ISSUE THREAD

**Issue by dibeja** [facebookincubator/facebook-for-magento#5]
Hi, I got this weird error on my magento site: checking the pixel through Facebook Pixel Helper it shows me that the PageView Event fires only through the NOSCRIPT pixel. Anyone has the same problem?
![senza titolo](https://user-images.githubusercontent.com/72047/30848920-ea1b4948-a2a0-11e7-8276-364287bba19f.jpg)

**Comment by dmitridr** [comment]
Hello, this is a longstanding issue. Pretty sure everyone has it.

The good news is that it's a bug in the actual 'Facebook Pixel Helper', the PageView event actually does fire normally. We have a team working on a fix but it's not a high priority for us. I'll close this task when it's done.

**Comment by dibeja** [comment]
Thanks

**Comment by vipulmishra341** [comment]
Hello,

We are also getting the same issue on our Magento website and as per the facebook support, they said issue with the Module itself. Can you please check and verify it your end?

Thanks in advance.

**Comment by dmitridr** [comment]
Hello,

Our help center does the best it can with limited information. However, we do have a workaround that doesn't make the pixel helper tool bug out by removing `source` and `version` params from the `noscript` section of the pixel fire. I'll send out a fix with that in 2.3.3, shortly.

**Comment by dmitridr** [comment]
Added the fix in [2.3.3](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.3.3), which removes the 'warning' of a second `PageView` fire, feel free to use this new version if you are concerned. 

Though since this ultimately does not affect the pixel fire, you should be okay with not upgrading if you so choose.
