### ISSUE TITLE
Facebook Shop Collections

### ISSUE THREAD

**Issue by dimitraros** [facebookincubator/facebook-for-magento#50]
Hi, i've updated the extension and my catalog was successfully connected to the shop section of my Facebook page. The problem is that now i have no option to create a collection in my facebook shop and i have a lot of products (old and new), so it's difficult to find what you want (there's only the search option). Is this happening because of the Facebook-Magento connection? If so, is there a way to add collections programmatically?

**Comment by dmitridr** [comment]
Hey, 

Thanks for writing in. This option was hidden for Magento shops, but we just enabled it. 
There should be a new tab appearing above your shop on FB in about 20 minutes that looks like this :

![shopconfig](https://user-images.githubusercontent.com/29133800/38395407-b1695148-38e7-11e8-9c46-39aeb51a1c10.png)

If you click on `Manage Shop` it will take you to an interface where you can create collections.
If that doesn't work, let us know!

**Comment by dimitraros** [comment]
Great, thanks a lot!

**Comment by andymcp16** [comment]
Hi,
This doesn't work for me. @dimitraros 

It says there are no products to add to the collection.
There are over 3k products in the synced catalogue.

Thanks in advance for any help you can give.

thanks,
Andrew
