### ISSUE TITLE
final price without discount - magento 1.9.2

### ISSUE THREAD

**Issue by sulfurio** [facebookincubator/facebook-for-magento#54]
Hello , i have installed successfully , and got the issue of price without discount shown .
The price is correct on calculation , but it show the price without discount on facebook , any help about it ?
Here the links to see : 

https://www.facebook.com/commerce/products/2095423690472874/

https://www.dragomoto.com/it/scarico-mivv-gp-kawasaki-z-1000-14-carbonio-k039l2s.html

**Comment by dmitridr** [comment]
Hello. There's an open issue about this with a workaround inside about how to edit the code to show the discount price.

It's here : #2 
Does the solution there work for you?

**Comment by dmitridr** [comment]
If you need to use a special solution for the price that involves a catalog rule, I would try inserting in the same spot specified in #2. There should already be a variable `$this->store_id` that you can reuse for the store_id.

**Comment by sulfurio** [comment]
Hi , special price ( to be applied on 1 singel product ) is different from catalog rules price ( discounts on many products , actually mostly used to apply discounts ) .  Here the modifications as suggested inside the piece of code about the final price (private function getFinalPrice) :+1: 
```
if ($price === null) {
     // $price = $product->getFinalPrice();
	 
    $discounted_price = Mage::getResourceModel('catalogrule/rule')->getRulePrice(Mage::app()->getLocale()->storeTimeStamp(FacebookAdsExtension::getDefaultStoreId()),
                                                      Mage::app()->getStore(acebookAdsExtension::getDefaultStoreId())->getWebsiteId(),0,$product->getId());


            if ($discountedPrice===false) { // if no rule applied for the product
                $price = $product->getFinalPrice();
            }else{
                $price = number_format($discountedPrice,2);
            }
    }
```
But the result is the same , blank page on the main facebook ads extension page 
Instead of Mage::getSingleton('customer/session')->getCustomerGroupId() i have put 0 , is that correct choice ?
Is probably something i do wrong because i didnt do the extension and also not much good on programming . Please help me to check where is the error.

**Comment by sulfurio** [comment]
ok it works now , a stupid typo error :+1: 
` if ($price === null) {
      
    $discountedPrice = Mage::getResourceModel('catalogrule/rule')->getRulePrice(Mage::app()->getLocale()->storeTimeStamp(FacebookAdsExtension::getDefaultStoreId()),
                                                      Mage::app()->getStore(FacebookAdsExtension::getDefaultStoreId())->getWebsiteId(),Mage::getSingleton('customer/session')->getCustomerGroupId(),$product->getId());


            if ($discountedPrice===false) { // if no rule applied for the product
               $price = $product->getFinalPrice();
            }else{
                $price = number_format($discountedPrice,2);
            }
    }`

this way the price with catalog rules will work , i suggest to make this change for the benefit of everyone

**Comment by dmitridr** [comment]
Glad you fixed it and it works for you. Please consider sending us a pull request!

**Comment by songofcode** [comment]
Hello, I'm facing the same problem on magento 1.9.4.4 sometimes prices are uploaded with discounts "from catalog rules" not special prices and now all prices are send without discount the feed takes the prices from the product directly without applying the discount rules
Any idea on how i can resolve this?
Thank you
