### ISSUE TITLE
Store View Synced with Facebook

### ISSUE THREAD

**Issue by golifter** [facebookincubator/facebook-for-magento#56]
Hello I have two store views, one for my Desktop store and one for mobile.
How can I sync only the products from the Mobile view?
I tried to change on the Advanced Options -> Synced with Facebook but it not working

Thank you

**Comment by dmitridr** [comment]
Hello,

After changing the option in advanced options, have you tried hitting `Fetch Now` in the `Manage Settings` screen under `Products` ?

**Comment by dmitridr** [comment]
Closing, hopefully that addressed your issue.
