### ISSUE TITLE
Adding Out of Stock Products

### ISSUE THREAD

**Issue by bedroomathletics** [facebookincubator/facebook-for-magento#6]
Hi there,

The extension adds all in stock **configurable** products by default. 

Trouble is, when all simple products are out of stock, the configurable does not change automatically (but it does prevent buying on front-end).

"Magento confirmed this is not part of Magento (Enterprise or Community). The parent (configurable) Stock Availability Status remains untouched regardless of what happens to any of it's children (simple)."

Therefore, we are submitting products to the Feed, where there is no simple product stock available and not available for purchase. 

I would do this manually, but we have thousands of products in our store :( 

Appreciate your help!

**Comment by dmitridr** [comment]
Hi again,

Thanks for writing in. This is certainly a relatively simple check we can add, my concern is that there might be some stores who want the availability status to remain 'in stock', for whatever reason. So we would have to provide a toggle for this behavior in the future, which will make this more involved.

**Comment by bedroomathletics** [comment]
I see, there is always that concern trying to keep everyone happy. A toggle would be absolutely perfect and help us solve this issue :)

**Comment by vipulmishra341** [comment]
Need to know when this toggle added in the module as the same issue we are facing.

**Comment by dmitridr** [comment]
Hello,

Just a heads up, we are not actively working on this specific issue at this time. However, if you'd like to send us a pull request with this feature, we would be more than happy to review and include it in the next version if it's good!

**Comment by ovidiulazar89** [comment]
Same problem here. Because the nature of configurable products , we get false "on stock" products, making the extension almost imposible to use. :(

**Comment by dmitridr** [comment]
Copied from another thread #70 about the same problem here:

Some sold out products that in the feed catalog appears as "in stock":

![captura de tela 2018-06-25 as 17 25 14](https://user-images.githubusercontent.com/32716130/41873918-caf6ccb8-789c-11e8-844e-8c5aad671e96.png)
Catalog ID: 195133271092736
Products links:
https://anurbanshop.com.br/marcador-mtn-marker-30.html
https://anurbanshop.com.br/camiseta-dgk-seduce-branca.html
https://anurbanshop.com.br/livro-upper-playground-grotesk-a-decade-of-swiss-design-lost-in-brooklyn.html

**Comment by dmitridr** [comment]
@leonardobussolo can you confirm that the products which incorrectly appear "in stock" are all configurable?

**Comment by leonardobussolo** [comment]
@dmitridr yes!

**Comment by dmitridr** [comment]
Looks like many people have had this problem for a long while, and nobody has jumped in to help, I will prioritize this feature to see if we can include a toggle as discussed above.

**Comment by leonardobussolo** [comment]
Any updates??

**Comment by dennisvdbrom** [comment]
Is there any new information available for this issue?

**Comment by dmitridr** [comment]
Not yet, but I hope to have this feature done by the end of the year. Thanks for your patience.

**Comment by dmitridr** [comment]
We've implemented the fix in [v2.6.2](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.6.2), please try it and if it doesn't work, open a new issue on us and reference this one! I tested it locally and it appeared to fix the problem for me. The solution was to call `isAvailable` on the configurable product in addition to checking it's stock. Keep in mind, this solution will likely slow down the feed upload, though I'm not certain by how much.
