### ISSUE TITLE
Not all product shows on file

### ISSUE THREAD

**Issue by SLdavid** [facebookincubator/facebook-for-magento#64]
The ext says one the file has different , can someone assist with the issue?

**Comment by dmitridr** [comment]
Hi. We need some more information to help: 

- Your plugin version. (Please use latest if you haven't tried it.)
- URL where you see the problem.
- Store ID (as seen on the plugin screen)
- Store URL
- (If you can) URL to one of the products on your site that is not `showing on the file` as you put it.

**Comment by dmitridr** [comment]
Closing since it has been many months. Please open a new issue if you are still having this problem and want assistance.
