### ISSUE TITLE
Facebook Catalog is showing errors

### ISSUE THREAD

**Issue by abhiagrawal87** [facebookincubator/facebook-for-magento#66]
When products are synced with Facebook using the extension then there is no error however the catalog shows following erros:

1. Missing **content_ids** or **contents** parameters from "Add to Cart" in <catalog_name>
2. Missing **content_type** parameter from "Purchase" in <catalog_name>
3. Missing **content_ids** or **contents** parameters from "View Content" in <catalog_name>
4. Missing "**Add to Cart**, **Purchase**" events in <catalog_name>
etc.

The Facebook Pixel Helper extension for Chrome shows all events being recorded and correct value being passed to Facebook still catalog shows the error.

<img width="377" alt="screen shot 2018-05-23 at 4 00 49 pm" src="https://user-images.githubusercontent.com/4506767/40419301-8b2ad192-5ea2-11e8-8219-064c095a6ac7.png">

![whatsapp-image-2018-05-17-at-2 11 38-pm](https://user-images.githubusercontent.com/4506767/40419360-bb27a898-5ea2-11e8-8a16-c16fa96137d7.png)

**Comment by dmitridr** [comment]
Hi, 

Looks like that could be a bug in the catalog interface.
Can you confirm that the pixel you are using on your site is the same as you blurred out in the screenshot?
Can you also give us your catalog ID? I will pass this to the catalog team to debug their interface.

**Comment by abhiagrawal87** [comment]
Hey! thank you for getting back to me. Here is the required information.

Pixel ID: 186235035178453
Catalog: 2115061915429174

**Comment by mengyingdu** [comment]
Hi @abhiagrawal87 ,

I check your catalog, it seems 100% match rate on all events now.
<img width="1095" alt="screen shot 2018-05-24 at 11 28 19 pm" src="https://user-images.githubusercontent.com/24535640/40529567-5ad7c38e-5faa-11e8-9431-173f53a5610a.png">
<img width="1147" alt="screen shot 2018-05-24 at 11 28 25 pm" src="https://user-images.githubusercontent.com/24535640/40529574-6088b874-5faa-11e8-9ba9-5f492ffc7b83.png">
<img width="1126" alt="screen shot 2018-05-24 at 11 29 15 pm" src="https://user-images.githubusercontent.com/24535640/40529580-64de34e4-5faa-11e8-893f-f3bdc4e551cc.png">


Thanks.

**Comment by abhiagrawal87** [comment]
Hey! the issue surprisingly seems to be gone. We were so worried from few days. Thanks much all for the help.

We encountered another issue wherein the Purchase event is showing invalid parameter. Can you help with this also?

![screen shot 2018-05-25 at 12 11 11 pm](https://user-images.githubusercontent.com/4506767/40530161-4d4a9082-6015-11e8-983c-479d578e84ff.png)

**Comment by mengyingdu** [comment]
I can't find the warning as your screenshot. It seems working. If you see any warning/error next time, can you wait a little bit since it maybe a temporary issues.
![screen shot 2018-05-25 at 8 47 00 am](https://user-images.githubusercontent.com/24535640/40553715-607341ee-5ff8-11e8-90b6-90d8a7926c2a.png)

Thanks.

**Comment by adrianluican** [comment]
I have the same problem. 

Catalog ID: 216869185790572
Pixel ID: 624996301216060

![facebookpixel](https://user-images.githubusercontent.com/39965036/40993374-23234b1e-6902-11e8-9c2c-5404a8cd5062.jpg)

**Comment by dmitridr** [comment]
Hi @adrianluican 

I checked your catalog, it seems events are coming in just fine now, I see a few add to carts and purchases. I think our backend systems merely needed some time to receive and process the events.

I'm closing this out as all issues appear to have been solved. Please open a new issue and reference this one if there is a similar problem again. Though my expectation is, this is merely a normal delay in seeing the events appear.

**Comment by yfundora** [comment]
Hello,
My Diagnostics catalog page look like that :

![image](https://user-images.githubusercontent.com/46605340/51048807-02585100-159a-11e9-8928-17a4dc4a09c9.png)

Event:
__FBT__eyJ0eXBlIjoidGV4dCIsImpzZmJ0IjoiTWlzc2luZyB7cGFyYW1ldGVyIG5hbWV9IHBhcmFtZXRlciBmcm9tIHtldmVudCBuYW1lfSBpbiB7cGl4ZWwvYXBwIG5hbWV9IiwiZGVzYyI6IlRpdGxlIG9mIHRoZSBpc3N1ZS4gVGhlcmUgaXMgYSBwYXJhbWV0ZXIgbWlzc2luZyBpbiB0aGUgcGl4ZWwgZXZlbnQsIHJlbGF0ZWQgdG8gbWlzc2luZyBldmVudHMgcGFyYW1zIGRpc3BsYXllZCBpbiB0aGUgZGlhZ25vc3RpYyBzZWN0aW9uIG9mIGNhdGFsb2cgbWFuYWdlciAjY2F0YWxvZ19kaWFnbm9zdGljcyIsInByb2plY3QiOiJwcm9kdWN0cyJ9__FBT__

Error:
__FBT__eyJ0eXBlIjoidGV4dCIsImpzZmJ0IjoiUmVxdWlyZWQgcGFyYW1ldGVyIHtwYXJhbSBuYW1lfSBpcyBtaXNzaW5nIGZyb20gbW9yZSB0aGFuIDIwJSBvZiB7ZXZlbnQgbmFtZX0gZXZlbnRzIGluIHRoZSBsYXN0IGRheSIsImRlc2MiOiJEZXNjcmlwdGlvbiBvZiBwaXhlbCBpc3N1ZSB3aGVyZSB0aGUgcmVxdWlyZWQgcGFyYW1ldGVyIGlzIG1pc3NpbmcgZnJvbSBhbiBldmVudCwgcmVsYXRlZCB0byBtaXNzaW5nIGV2ZW50cyBwYXJhbXMgZGlzcGxheWVkIGluIHRoZSBkaWFnbm9zdGljIHNlY3Rpb24gb2YgY2F0YWxvZyBtYW5hZ2VyICNjYXRhbG9nX2RpYWdub3N0aWNzIiwicHJvamVjdCI6InByb2R1Y3RzIn0=__FBT__

Catalog ID: 141496353394226
Pixel ID: 229198024300131

Thanks!
