### ISSUE TITLE
Hackers are fishing/searching for your code on live servers.

### ISSUE THREAD

**Issue by RogerKeulen** [facebookincubator/facebook-for-magento#7]
I get some requests at my servers for your code.
**_Blocked-Ip: /facebookadstoolbox/productfeed/gen_**

Please make shure your code is save to use.
Always install honeypot and check your logs.

**Comment by dmitridr** [comment]
Hello,

Thanks for your concern. We are not aware of any outstanding security issues, the newest version should be secure.

If you have the plugin installed, `/facebookadstoolbox/productfeed/gen` is a URL Facebook uses to trigger the feed regeneration mechanism (by default once a day) before fetching the feed file, so this endpoint will be queried from Facebook. It's true that this endpoint can be queried by others, but there is a cache preventing the feed from being regenerated too often to cause a DDoS. [Details are in the code](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/code/community/Facebook/AdsExtension/Model/Observer.php#L105).

I can think of a couple of ways to secure this endpoint even further to prevent non-Facebook queries entirely, if that is a concern.

**Comment by dmitridr** [comment]
Closing, we have had no reported security problems for over a year now with this plugin, so I don't think we need to go overboard with security enhancements at this time.
