### ISSUE TITLE
In Stock Items Displayed as Out of Stock in Facebook Shop

### ISSUE THREAD

**Issue by csbrou** [facebookincubator/facebook-for-magento#73]
My problem is slightly different from some of the other inventory issues discussed here. In my case, all of our items are in stock. They display as In Stock in the Facebook Business Manager Catalog feed that is generated using this plugin. However, when you go to the Shop tab on our Facebook Page, they are all listed as Out of Stock. 

When I originally set up the feed about a month ago, everything was working correctly but something has changed since then. Any suggestions or ideas as to why this is happening.

**Comment by dmitridr** [comment]
Hi, about a month ago we had a severe issue where all FB shops had all products marked out of stock.
If you do a full reset of the plugin `Settings > Advanced Options > Delete` , and set up again, the problem should be fixed.

If you don't want to do a reset, if you give us your catalog ID we can try to apply a manual resolution, though this will take longer.

**Comment by csbrou** [comment]
Worked perfectly. Thank you so much!
