### ISSUE TITLE
Content ID doesn't match

### ISSUE THREAD

**Issue by caffydee** [facebookincubator/facebook-for-magento#74]
Pixel is using Magento SKU as Content ID
Feed is using Magento Product ID as Content ID

**Comment by mengyingdu** [comment]
What's your store url?

**Comment by mengyingdu** [comment]
If you are not using the latest version, can you upgrade and resync ? We saw this problems for old version before.

**Comment by caffydee** [comment]
We'll give an upgrade a go. Thanks

**Comment by caffydee** [comment]
That looks to have worked. Thanks.
