### ISSUE TITLE
Package Missing From composer

### ISSUE THREAD

**Issue by dgitman** [facebookincubator/facebook-for-magento#77]
$ composer require facebook/facebook-for-magento 
                                                                                                                                                  [InvalidArgumentException]
Could not find a matching version of package facebook/facebook-for-magento. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by mengyingdu** [comment]
Are you using magento 2? It hasn't been supported yet see #24

**Comment by mengyingdu** [comment]
And many discussion about problems when using composer to upgrade https://magento.stackexchange.com/questions/98332/how-to-update-magento2-using-composer

**Comment by andrewdaluz** [comment]
You point github' repository on your composer using this commands, manually:
    composer config repositories.facebook git git@github.com:facebookincubator/facebook-for-magento.git
    composer require facebook/facebook-for-magento 2.5.1
