### ISSUE TITLE
TSV File Not Using/Generating 'Gender' Attribute

### ISSUE THREAD

**Issue by bedroomathletics** [facebookincubator/facebook-for-magento#8]
Hi Guys,

I am trying to create a product set in my Facebook product catalogue. The problem is, the .tsv file generated by the extension does not use the 'gender' attribute.

Therefore, we are unable to split our catalogue into 'mens' and 'womens'. 

I have already created rules to suit our Magento store such as this;

COLUMN | RULE
gender | Replace regex - 'Men' - 'Male'

Any help would be appreciated :+1:

**Comment by bedroomathletics** [comment]
As this has been changed to a feature request, can I confirm this isn't possible as of yet, rather than me making a mistake? :)

**Comment by dmitridr** [comment]
As far as I can tell it's not possible currently. Though we do export the category names, so If you have separate categories for 'Mens' and 'Womens' assigned to products you should be able to create Mens/Womens product sets based on the category.

**Comment by bedroomathletics** [comment]
Thanks for the reply! 

Category names in 'product_type' column? Unfortunately it grabs the categories in a nested way. 

E.g.

Collection \|   Collection > Womens > Womens Slippers > Slipper Boots \| Collection   > Sale \| Collection > Sale > Womens Sale \| Collection > Sale >   Womens Sale > Slippers Sale
--

Would be helpful is we could assign which of our Magento attributes we can export for the feed. So i could choose our 'gender' attribute and then map that to the facebook gender field :+1:

**Comment by dmitridr** [comment]
That's a good suggestion, we'll think about maybe a settings page where users can do that mapping.

In terms of the category names, I think you might be able to build a product set rule using the contains 'Womens' or contains 'Mens'. 

But in any case, we should have an update to explicitly export the gender soon. @tahoff is working on supporting the gender attribute, we should have it by the next release.

**Comment by bedroomathletics** [comment]
Thanks fore the update! :)

**Comment by dmitridr** [comment]
@tahoff added this feature in v2.3.4, please try it out. 
https://github.com/facebookincubator/facebook-for-magento/releases

If it's still not working for you, feel free to re-open the issue or open another one!
