### ISSUE TITLE
Multi-store multi-feed

### ISSUE THREAD

**Issue by jmifarma** [facebookincubator/facebook-for-magento#88]
Hello,

do you plan to add this anytime soon?

thank you

**Comment by dmitridr** [comment]
Hello, 

Thanks for writing in! No we do not plan on adding this, but we are tracking requests for this in Issue #20. Please consider commenting in that thread to show support for this issue, it helps us prioritize.

If you are a developer, please consider sending us a pull request to add the functionality described, we are more than happy to review it and merge it!
