### ISSUE TITLE
Try to connected to another sotre.

### ISSUE THREAD

**Issue by gizmocn** [facebookincubator/facebook-for-magento#92]
I try to connected to another store ID, then I remove all plugin files and clear cache and reinstall it again, when I click Facebook Ads Extension, it show it still connected to old store id. 

I click settings, I got error message:

You don't have permission to advertise for ....
To run this plugin with Facebook, you must be an admin or editor of the Page connected to this Magento store. Please contact the admin of ... to be assigned to one of these roles before creating ads.

Any one can help, how can I disconnect the old store id and then connected to new one.

**Comment by dmitridr** [comment]
Hi,

This feature is not supported using the UI, but you can do it by editing the DB. 

#69 covers how to remove the pixel id from the Database.
You can use the same procedure to remove the store id, the name of the store id field in the database is `facebook_ads_toolbox/dia/setting/id` . If you remove this field you should be able to run setup again.

Please let me know if you have questions. There are alternative methods to do this as well, but they are more advanced.

**Comment by dmitridr** [comment]
Closing as there hasn't been a response in a while. Hope that solved your issue.
