### ISSUE TITLE
PHP 7.2 compatability

### ISSUE THREAD

**Issue by scottcdi** [facebookincubator/facebook-for-magento#94]
Magento just recently announced that they will be openly supporting PHP 7.2 for the magento 1 instance and have also recently just released a patch. 

Does anyone know if this plugin will be compatible with PHP 7.2 or if a patch is planning on being developed here as well?

**Comment by dmitridr** [comment]
We have not tried it on 7.2, but it should work at long as 7 is compatible with 7.2. If you try it and it doesn't work please let us know in this thread.

**Comment by dmitridr** [comment]
Closing as there hasn't been a response in a while.
