### ISSUE TITLE
Pixel and Catalog properly paired but IDs are not being received. 

### ISSUE THREAD

**Issue by argentjustlane** [facebookincubator/facebook-for-magento#96]
I paired a few Pixel with my Catalog. For two Pixel, it seems like the IDs of the Catalog is not being received. Please help. 
![atta 1](https://user-images.githubusercontent.com/43842239/46458733-514b5900-c7e9-11e8-9421-2f3b0611ea78.png)
![atta 3](https://user-images.githubusercontent.com/43842239/46458737-527c8600-c7e9-11e8-8908-16b273e04b6e.png)
![atta 4](https://user-images.githubusercontent.com/43842239/46458739-53151c80-c7e9-11e8-9280-7cdf720b6cf3.jpg)

Am I doing anything wrong?

**Comment by dmitridr** [comment]
Hello,

I checked out your site. If you click on `url called : show` in the pixel helper you will see the phrase `googletagmanager`. The pixel that you see is from google tag manager, not from our plugin.

If you would like to use our facebook-for-magento plugin, I would recommend you remove the pixel from google tag manager and then configure the plugin to use the pixel via the configuration screen in the admin panel, it should solve the problem.

It may be possible to get google tag manager working as well, but I cannot help you very much with this, as this is outside of my expertise. It's possible you may have some success if you create a new pixel and associate it with the one catalog that you would like to use.

Hope that helps.

**Comment by argentjustlane** [comment]
Thanks! Let me try first this weekend. Will tell you how it goes. Thanks again.

**Comment by dmitridr** [comment]
I trust that it went well? In any case I will close this task, please open a new one and reference this one if it didn't work.
