### ISSUE TITLE
(not issue) M2 migration

### ISSUE THREAD

**Issue by wrux** [facebookincubator/facebook-for-magento#97]
This isn't an issue, but I didn't know where else to ask. 

Is there a Magento 2 version of this extension in the works?

**Comment by dmitridr** [comment]
Hello, thanks for writing in. @liyu1981 has something initial in the works, but I can not speak for an ETA. Please see the existing issue #24 which has some historical discussion.

**Comment by hiimkhaled** [comment]
Any update?
